name: Daily Commit

on:
  schedule:
    # Runs every day at 04:20 UTC
    - cron: '20 4 * * *'
  workflow_dispatch:  # for manual testing

permissions:  
  contents: write

  
jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a dummy change
        run: |
          date > timestamp.txt

      - name: Commit and push - 23f2002348@ds.study.iitm.ac.in
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add timestamp.txt
          git commit -m "Automated daily commit"
          git push
