name: 23f2002348@ds.study.iitm.ac.in
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * * git commit -m "Sample" >/dev/null 2>&1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Running
      run: |
        echo "Running!"
